### ISSUE TITLE
recession shading doesn't work in firefox

### ISSUE THREAD

**Issue by benzipperer** [equitablegrowth/Playfair#106]
I couldn't get the recession shading to appear. Can you provide some data where it works so I can see what I'm doing wrong?

I wasn't able to obtain a recession with the following data, for instance:

Value	time
79.6	10/01/2007
79.7	11/01/2007
79.7	12/01/2007
80.0	01/01/2008
79.9	02/01/2008
79.8	03/01/2008
79.6	04/01/2008
79.5	05/01/2008
79.4	06/01/2008
79.2	07/01/2008
78.8	08/01/2008
78.8	09/01/2008
78.4	10/01/2008
78.1	11/01/2008
77.6	12/01/2008
77.0	01/01/2009
76.7	02/01/2009
76.2	03/01/2009
76.2	04/01/2009
75.9	05/01/2009
75.9	06/01/2009
75.8	07/01/2009
75.6	08/01/2009
75.1	09/01/2009
75.0	10/01/2009
75.2	11/01/2009
74.8	12/01/2009

**Comment by austinclemens** [comment]
This worked for me - the date has to be the x-variable. I pasted in this exactly and x,y was date,value:

value,date
79.6,10/01/2007
79.7,11/01/2007
79.7,12/01/2007
80.0,01/01/2008
79.9,02/01/2008
79.8,03/01/2008
79.6,04/01/2008
79.5,05/01/2008
79.4,06/01/2008
79.2,07/01/2008
78.8,08/01/2008
78.8,09/01/2008
78.4,10/01/2008
78.1,11/01/2008
77.6,12/01/2008
77.0,01/01/2009
76.7,02/01/2009
76.2,03/01/2009
76.2,04/01/2009
75.9,05/01/2009
75.9,06/01/2009
75.8,07/01/2009
75.6,08/01/2009
75.1,09/01/2009
75.0,10/01/2009
75.2,11/01/2009
74.8,12/01/2009

**Comment by benzipperer** [comment]
OK, the problem appears to be just with Firefox (43.0.3). The recession bar
worked perfectly for me in Chrome.
