### ISSUE TITLE
black box from editing axes number still sticks around after editing is done

### ISSUE THREAD

**Issue by nbunker** [equitablegrowth/Playfair#122]
![wage growth to pass-through total](https://cloud.githubusercontent.com/assets/9907459/12569297/78d339de-c39b-11e5-882c-b5f88e37d780.png)

**Comment by austinclemens** [comment]
You should just have to click once on the graph area to turn this off but it occurs to me that saving/loading could break that functionality so I am going to fix that problem and also this issue where there is a space after tick labels
