### ISSUE TITLE
Change web hosts

### ISSUE THREAD

**Issue by austinclemens** [equitablegrowth/Playfair#132]
if it is in either an input or in chartobject. encoding the whole object/inputs doesn't seem to help.  So that's super weird.

**Comment by austinclemens** [comment]
using encode doesn't help. Quite possibly all strings will have to be converted to hex or something - see here: http://stackoverflow.com/questions/21647928/javascript-unicode-string-to-hex

**Comment by austinclemens** [comment]
check encodings...

var data = "{name: 'Bob', occupation: 'Plumber'}";
var url = 'data:text/json;charset=utf8,' + encodeURIComponent(data);
window.open(url, '_blank');
window.focus();

**Comment by benzipperer** [comment]
I also can't save with the following data and a line graph with x=year, y=value

year	group	race	value
1983	union	Black	31.66576
1983	union	White	22.19861
1984	union	Black	29.13143
1984	union	White	20.47474
1985	union	Black	27.28796
1985	union	White	19.47467
1986	union	Black	26.54934
1986	union	White	18.96236
1987	union	Black	25.30173
1987	union	White	18.33323
1988	union	Black	25.85546
1988	union	White	18.09342
1989	union	Black	25.19995
1989	union	White	17.78374
1990	union	Black	24.076
1990	union	White	17.58265
1991	union	Black	23.97493
1991	union	White	17.32142
1992	union	Black	23.86945
1992	union	White	16.99364
1993	union	Black	23.44333
1993	union	White	16.95483
1994	union	Black	22.93449
1994	union	White	16.82627
1995	union	Black	22.19846
1995	union	White	16.0807
1996	union	Black	21.20204
1996	union	White	15.8119
1997	union	Black	20.06371
1997	union	White	15.39517
1998	union	Black	19.68725
1998	union	White	15.08889
1999	union	Black	19.16647
1999	union	White	15.06071
2000	union	Black	18.86562
2000	union	White	14.67107
2001	union	Black	18.67358
2001	union	White	14.67656
2002	union	Black	18.77297
2002	union	White	14.4335
2003	union	Black	18.13474
2003	union	White	14.16736
2004	union	Black	16.60826
2004	union	White	13.92787
2005	union	Black	16.49849
2005	union	White	13.73634
2006	union	Black	16.03011
2006	union	White	13.27554
2007	union	Black	15.73059
2007	union	White	13.48645
2008	union	Black	15.53941
2008	union	White	13.97727
2009	union	Black	15.3295
2009	union	White	13.82743
2010	union	Black	14.96798
2010	union	White	13.37651
2011	union	Black	14.92705
2011	union	White	13.30529
2012	union	Black	14.46049
2012	union	White	12.65396
2013	union	Black	14.85387
2013	union	White	12.64046
2014	union	Black	14.27225
2014	union	White	12.47151
2015	union	Black	14.24854
2015	union	White	12.47033

**Comment by benzipperer** [comment]
It turns out playfair is anti-union. I can't save a line graph with data

a,b
1,2
3,4

when "union" is in the headline or source or whatever.

**Comment by austinclemens** [comment]
Well this is, of course, by design. Filthy unions!

**Comment by austinclemens** [comment]
After muuuuuch trial and error and reflection, it looks like the best way to fix this is to change hosts, as this is all the fault of some script on wirenine that looks for SQL strings and rejects server requests.
