### ISSUE TITLE
No way to label line data

### ISSUE THREAD

**Issue by kvaghul** [equitablegrowth/Playfair#191]
Labeling the data points in a line isn't possible right now. The hack around labeling data for a line graph is to use the settings to reduce the size of the points, add a point graph and have that be labeled. But this could become a little cumbersome/isn't intuitive for a non-frequent Playfair user. 

![screen shot 2016-06-24 at 3 11 41 pm](https://cloud.githubusercontent.com/assets/19979601/16348100/83e2a180-3a1e-11e6-8440-ed2a32c95d61.png)

With hack:
![screen shot 2016-06-24 at 3 12 43 pm](https://cloud.githubusercontent.com/assets/19979601/16348103/87626354-3a1e-11e6-8abb-b9952a1e098f.png)

**Comment by austinclemens** [comment]
open question for @kvaghul and others: what would the best user interface for this be? Right now one thing you could do is use the Text element to label them - you could just use the same x and y as you do for the line (with a new var that would be the label with values missing if you don't want to label everything or just use Y as the label).

One possibility is to have points appear on mouseover of a particular part of the line and allow a right-click to label. This is a bit tricky to code but certainly possible... would this be the right interface? Or is it something else I haven't thought of?
