### ISSUE TITLE
Glitch on numbers for y-axis for line graph

### ISSUE THREAD

**Issue by nbunker** [equitablegrowth/Playfair#71]
![playfair_graph](https://cloud.githubusercontent.com/assets/9907459/11873352/02d55378-a4a8-11e5-8827-1d0e2e92d07c.png)

**Comment by austinclemens** [comment]
If anyone else sees this issue please leave a comment here

**Comment by austinclemens** [comment]
http://stackoverflow.com/questions/34400758/base64-encoded-font-some-characters-glitchy-under-windows
