### ISSUE TITLE
exported a graph and file had no title, axes labels, etc.

### ISSUE THREAD

**Issue by nbunker** [equitablegrowth/Playfair#75]
![playfair_graph](https://cloud.githubusercontent.com/assets/9907459/11935899/6e26aac2-a7d8-11e5-94b2-93da5f9c0adf.png)

On the second attempt the graph came out fine, but first time it was all messed up

**Comment by austinclemens** [comment]
this kinda thing is hard to trouble shoot - if you see it again, get me when it happens so I can take a look at it in the browser

**Comment by austinclemens** [comment]
gonna close this since it hasn't been reproduced since then.
