### ISSUE TITLE
unable to draw data after turning off custom axes

### ISSUE THREAD

**Issue by nbunker** [equitablegrowth/Playfair#90]
I pasted in new data, hit redraw, realized custom axes were still on, and once I turned them off, Playfair wasn't able to process the new data anymore.

**Comment by austinclemens** [comment]
It's possible that this was not about custom axes but rather was because you needed to put in your variables again. Whenever you paste in new data, all the variable fields reset and you need to re-do them.

**Comment by austinclemens** [comment]
Going to close this because it is part of a big custom axis re-write that I have on the board already
